#!/bin/bash

set -euo pipefail

. common

gcloud compute scp "$1" $INSTANCE_NAME:/home/kimstebel/content.jpg
echo uploaded content image
gcloud compute scp "$2" $INSTANCE_NAME:/home/kimstebel/style.jpg
echo uploaded style image
gcloud compute scp ~/repos/neural-style/th-script $INSTANCE_NAME:/home/kimstebel/th-script
echo uploaded script
gcloud compute ssh $INSTANCE_NAME --command ./th-script
echo executed script
gcloud compute scp $INSTANCE_NAME:/home/kimstebel/out.jpg "$3"
echo copied result


