#!/bin/bash

set -euo pipefail

docker run --runtime=nvidia --rm -v "$HOME:/kim" kimstebel/style-transfer \
  /torch/install/bin/th neural_style.lua \
    -style_image /kim/style.jpg \
    -content_image /kim/content.jpg \
    -output_image /kim/out.jpg \
    -print_iter 200 \
    -save_iter 0 \
    -backend nn \
    -image_size 512 \
    -style_scale 10.0 \
    -original_colors 1 \
    -content_weight 5e0 \
    -style_weight 1e2 \
    -tv_weight 1e-3
